<a href="https://colab.research.google.com/github/mustafaozsahinn/daily-work/blob/main/november30.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
from scipy import stats

In [27]:
m = np.arange(8)
m

array([0, 1, 2, 3, 4, 5, 6, 7])

In [28]:
# split(x, 4) eşit parçaya böler
np.split(m1, 4)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7])]

In [29]:
# split() ile indexleyerek bölebilriiz
np.split(m1, [2])

[array([0, 1]), array([2, 3, 4, 5, 6, 7])]

In [30]:
# split() ile indexleyerek farklı şekilde de bölebilriiz
np.split(m1, [2, 4])

[array([0, 1]), array([2, 3]), array([4, 5, 6, 7])]

In [36]:
m2 = np.arange(20).reshape(5, 4)
m2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [37]:
# yine indexleyerek bölebiliriz
np.split(m2, [1, 3])

[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [38]:
# yine indexleyerek bölebiliriz
np.split(m2, [1, 3], axis = 0)

[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [39]:
# vsplit ile bölebiliriz
np.vsplit(m2, [1, 3])

[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [40]:
# değişkenleri atama yapabiliriz.
upper, lower = np.split(m2, [3])

In [41]:
upper

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
lower

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [43]:
# hsplit ile bölebiliriz
np.hsplit(m2, [1, 3])

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]), array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]), array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [44]:
left, right = np.hsplit(m2, [3])

In [45]:
left

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18]])

In [46]:
right

array([[ 3],
       [ 7],
       [11],
       [15],
       [19]])

In [47]:
v = np.array([2, 1, 4, 3, 5])
v

array([2, 1, 4, 3, 5])

In [48]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [51]:
v.sort()
v

array([1, 2, 3, 4, 5])

In [53]:
twoD = np.random.randint(5, 100, (3, 3))
twoD

array([[95, 23, 50],
       [54, 52, 85],
       [90, 78, 74]])

In [55]:
# axis = 0 olduğu için yukarıdan aşağıya sıralar
np.sort(twoD, axis = 0)

array([[54, 23, 50],
       [90, 52, 74],
       [95, 78, 85]])

In [56]:
# axis = 1 olduğu için sütunlarda sıralar
np.sort(twoD, axis = 1)

array([[23, 50, 95],
       [52, 54, 85],
       [74, 78, 90]])

In [57]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr[8]

8

In [59]:
arr[-3]

8

In [60]:
arr[1:5]

array([1, 2, 3, 4])

In [61]:
arr[1::2]

array([1, 3, 5, 7, 9])

In [62]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10])

In [63]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [67]:
# 1 tane indexleme yaparsak satırı verir.
arr_2d[1]

array([20, 25, 30])

In [69]:
# 2 değer girersek, row ve column a karşılık gelir
arr_2d[1,1]

25

In [70]:
# aynı zamanda iki index de yapılabilir.
arr_2d[1][1]

25

In [71]:
type(arr_2d[1][1])

numpy.int64

In [72]:
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [73]:
# slice lama neticesinde yine array sonuç verir
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [74]:
arr_2d[2:,:2]

array([[35, 40]])

In [83]:
# indexleme ile yeni atama yapabiliriz.
# mutable olduğu için kalıcı olarak değişir
arr_2d[1,1] = 55
print(arr_2d)

[[ 5 10 15]
 [20 55 30]
 [35 40 45]]


In [84]:
# array içinde tek tip olur.
# float değer atasak da int sonuç verir.
arr_2d[1,1] = 55.9
print(arr_2d)

[[ 5 10 15]
 [20 55 30]
 [35 40 45]]


In [87]:
# birden fazla index no girilecekse liste halinde gönderilir.
v = np.arange(0, 30, 3)
v[[1,3,7]]

array([ 3,  9, 21])

In [192]:
# 2 dimension da deneyelim
arr2d = np.zeros((10, 10), dtype=int)
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [193]:
# shape sonucu tuple gelir
arr2d.shape[0] # ile satır sayısını buluruz.

10

In [94]:
# her satıra bir numara atama için
# bu şekilde hepsini değiştirmek vectorisation oluyor.
for x in range(arr2d.shape[0]):
  arr2d[x] = x
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [96]:
  # sıralarını istediğimiz gibi çağırabiliriz
  arr2d[[6,3,9]]

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [97]:
jj = np.arange(1,17).reshape(4,4)
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [100]:
# 1. satır 0. sütun
jj[1,0]

5

In [103]:
# fancy indexleme için eşit sayıda olmalı!
jj[[1,2],[0,3]]

array([ 5, 12])

In [218]:
# aradaki , önemli. birden çok değeri indexleyebiliyoruz
jj[[2],[0,2,3]]

array([ 9, 11, 12])

In [232]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [242]:
# jj[1:3][1:3] yapınca sırayla işlem yapar.
kk = jj[1:3]
kk

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [243]:
kk[1:5]

array([[ 9, 10, 11, 12]])

In [234]:
jj[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [106]:
# basic ve fancy index ortak kullanımı
# ilkinde 1 aynı satır olduğu için çalışır
jj[[1],[1,3]]

array([6, 8])

In [109]:
# istenen sütunların tüm satılarını almak için : kullanırız.
jj[:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [111]:
# ilki basic ikincisi fency index
jj[1:3, [1,3]]

array([[ 6,  8],
       [10, 12]])

In [112]:
# condition üzerinden bir selecting yapma
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [113]:
# bu condiditon ı sağlaynalar True verir
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [114]:
# True olanları select eder getirir.
cond = arr > 4
arr[cond]

array([ 5,  6,  7,  8,  9, 10])

In [115]:
# condition ı doğrudan uygularız
arr[arr < 6]

array([1, 2, 3, 4, 5])

In [117]:
# multi conditonal selection
arr[(arr != 3) & (arr != 4)]

array([ 1,  2,  5,  6,  7,  8,  9, 10])

In [119]:
# broadcasting yayma demek
arr[:5] = 77
arr

array([77, 77, 77, 77, 77,  6,  7,  8,  9, 10])

In [121]:
# listede broadcasting yapamıyoruz.
a = [0, 2, 4, 6]
# a[0:3] = 100 dersek hata olur
a[0:3] = 100, 100, 100, 100 
# yapmak gerek
a

[100, 100, 100, 100, 6]

In [124]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [125]:
slice_of_arr = arr[0:6]
slice_of_arr

array([1, 2, 3, 4, 5, 6])

In [126]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [128]:
# kalıcı olarak değişiyorlar
arr

array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [133]:
arr_copy = arr.copy()
arr_copy[:6] = [0, 1, 2, 3, 4, 5]
arr_copy

array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10])

In [138]:
arr = np.arange(1,5)

In [139]:
arr + arr

array([2, 4, 6, 8])

In [140]:
1 / arr

array([1.        , 0.5       , 0.33333333, 0.25      ])

In [141]:
import warnings
warnings.filterwarnings('ignore')

In [142]:
# her elemandan 1 çıkarmak - subtrack
np.subtract(arr, 1)

array([0, 1, 2, 3])

In [144]:
# toplama için add ile vectorisation yaparız
np.add(arr, 2)

array([3, 4, 5, 6])

In [145]:
# çarpma multiply
np.multiply(arr, 3)

array([ 3,  6,  9, 12])

In [146]:
# üssü power ile
np.power(arr, 2)

array([ 1,  4,  9, 16])

In [147]:
# sadece 3ten büyük olanların modülüs 2sini alın
np.mod(arr[arr>3], 2)

array([0])

In [148]:
x1 = np.arange(9.0).reshape(3, 3)
x2 = np.arange(3.0)

In [149]:
# 3x3 matisten 1x3 matirsi çıkarabiliriz
np.subtract(x1, x2)

array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])

In [150]:
# tersi de mümkün
np.subtract(x2, x1)

array([[ 0.,  0.,  0.],
       [-3., -3., -3.],
       [-6., -6., -6.]])

In [152]:
# bir fonksiyonun universal olup olmadığına type ufunc ile kontrol ederiz.
print(type(np.add))
print(type(np.concatenate))

<class 'numpy.ufunc'>
<class 'function'>


In [154]:
#matematiksel işlemleri np ile yapabiliriz
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [156]:
# özel işlemler de mümkün
np.log10(1000)

3.0

In [158]:
# istatikssel işlemleri
v = np.array([1,1,2,2,3,3,3])
np.mean(v)

2.142857142857143

In [159]:
# diğer mean fonc
v.mean()

2.142857142857143

In [160]:
# istatistiksel işlemleri (sıralama gibi) de yapar.
arry = np.array([4,7,1,9,1,2,6,8,10])
# median sıralı ortancadır.
np.median(arry)

6.0

In [164]:
arry.min()

1

In [163]:
# peak to peak
np.ptp(arry)

9

In [165]:
# random içinde seed
np.random.seed(42)

In [166]:
# randn normal dağılımlı bir random array elde ederiz.
xarr = np.random.randn(3, 5)
xarr

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337],
       [-0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783]])

In [168]:
# seed ile sabitleme yaparız
np.random.seed(42)
xarr = np.random.randn(3, 5)
xarr

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337],
       [-0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783]])

# PANDAS
pre class bireysel çalışma + ders notları

In [3]:
ser = pd.Series(list("clarusway"))
ser

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

In [177]:
xxarr = np.array([10, 20, 30])

In [179]:
# index number ile value lenght eşit olmalı.
pd.Series(data = xxarr, index = [1,2,3])

1    10
2    20
3    30
dtype: int64

In [182]:
# dictionaryden seri oluşturuyor. adam adam
d = {"a": 10, "b": 20, "c":30}
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [187]:
# index e optional değer girebilirir.
# isimleri olan keylerin value ları gelir. diğerleri NaN
# ayrıca index sayısı farklı index kadar sonuç çıkarır.
pd.Series(data = d, index = ["q", "c", "y", "p"])

q     NaN
c    30.0
y     NaN
p     NaN
dtype: float64

In [189]:
# tek bir değer ile daahi seri oluşturabiliriz
# index i çoğaltırsak hepsine aynı değer verir.
pd.Series(data = "mustafa", index = range(3))

0    mustafa
1    mustafa
2    mustafa
dtype: object

In [190]:
# sclar değerlerle seri oluşturabiliriz
pd.Series(data = 10, index = ["a", "b", "c", "d"])

a    10
b    10
c    10
d    10
dtype: int64

In [ ]:
### burda ders bitti ###

In [4]:
ser.sort_values(ascending = True)

2    a
7    a
0    c
1    l
3    r
5    s
4    u
6    w
8    y
dtype: object

In [5]:
ser.sort_index(ascending = False)

8    y
7    a
6    w
5    s
4    u
3    r
2    a
1    l
0    c
dtype: object

In [6]:
# index numarsına göre bakıyor
ser.isin(["a"])

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7     True
8    False
dtype: bool

In [7]:
ser.keys()

RangeIndex(start=0, stop=9, step=1)

In [8]:
ser.values

array(['c', 'l', 'a', 'r', 'u', 's', 'w', 'a', 'y'], dtype=object)

In [9]:
# on the air olarak çıkıyor
ser.items()
# o yüzden list ile çıkarıyoruz
list(ser.items())

[(0, 'c'),
 (1, 'l'),
 (2, 'a'),
 (3, 'r'),
 (4, 'u'),
 (5, 's'),
 (6, 'w'),
 (7, 'a'),
 (8, 'y')]