<a href="https://colab.research.google.com/github/mustafaozsahinn/daily-work/blob/main/kadir.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
kadir = np.arange(36).reshape(6,6)
print(kadir)
print(kadir[1,2])
print(kadir[2,3])
print(kadir[3,4])
print(kadir[4,5])
print(kadir[0,4:6])
print(kadir[4,4:6])
print(kadir[5,4:6])
kkadir = kadir[kadir < 30] 
print(kkadir[kkadir % 5 == 0])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
8
15
22
29
[4 5]
[28 29]
[34 35]
[ 0  5 10 15 20 25]


In [24]:
a = np.arange(36).reshape(6,6)
np.array([a[1,2],a[2,3],a[3,4],a[4,5]])

array([ 8, 15, 22, 29])

In [27]:
np.array([a[0,4:6],a[4,4:6],a[5,4:6]])

array([[ 4,  5],
       [28, 29],
       [34, 35]])

In [32]:
kadir = a[a < 30]
kadir[kadir % 5 == 0]

array([ 0,  5, 10, 15, 20, 25])